### ISSUE TITLE
Problem with OpenMP-parallel thermal Monte Carlo

### ISSUE THREAD

**Issue by J-LV** [dullemond/radmc3d-2.0#22] opened 2022-06-30 15:29 UTC
Dear all,
I am a PhD student who uses RADMC-3D to model interplanetary dust. I have used the conventional thermal MC to compute the dust temperature of my model, but it was a very time-consuming process (due to the employed dust density). So, I have tried the OpenMP-parallel version, getting wrong results. I am aware that parallel thermal MC is not tested in all cases, despite that, I want to reflect what I suppose the problem is.
I will use the run_simple_1 example with some changed parameters to illustrate a similar scenario where parallel thermal does not work well. I think that the problem appears when I set the star outside the grid at a distance much larger that the grid size. The changed parameters of run_simple_1 are:
sizex = sizey = sizez = 100e5
radius = 50e5
pstar = np.array([au, 0., 0.]) 
With this configuration, temperature computed with the conventional mctherm differs from the parallelized one.
If neither OpenMP-parallel nor MRW seems to work with this configuration, is there any other solution to accelerate the thermal MC process with this model configuration and a high density?
Thank you.
Best regards,
Jennifer

**Comment by dullemond** [comment] 2022-06-30 16:19
Hi Jennifer,
ouch, that shouldn't happen. I need to look into this! Did you make sure to pull the latest version of RADMC-3D from github?
Cheers,
Kees

**Comment by J-LV** [comment] 2022-06-30 17:31
Yes, I have the latest version. In fact, I updated it because I saw the bugfix of the OpenMP-parallel thermal MC with multiple species.
Thank you so much for your quick answer.
Jennifer

**Comment by dullemond** [comment] 2022-07-01 18:41
Hi Jennifer,

I found the cause of the problem. It was a bug in the code. When a star is outside of the grid (to be precise: farther from the center of the grid than the farthest cell of the grid), RADMC-3D focuses the MC photon packages emitted by the star into the direction of the grid. This is necessary especially when the star is far away, because otherwise RADMC-3D wastes most of its photon packages completely missing the grid. This mode uses the `star_fraclum` array from the `stars_module`. For some reason this array was declared threadprivate, yet it was only computed for the master thread, while it was kept 1.0 for all other threads. This meant that for all other threads the focusing failed. 

I now fixed the problem by removing the threadprivate declaration, and some other minor modifications necessary now that `star_fraclum` is no longer threadprivate. Some quick tests appear to show that the problem has been fixed now. 

It is committed and pushed to the master branch.

Thanks a lot for being a careful modeller, and for reporting this issue! Thanks to people like you, I can improve the code.

Best wishes,
Kees

**Closed by dullemond** 2022-07-01 18:41 UTC
